name: crashdetection
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.1.2 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.6
  sensors_plus: ^3.0.3
  geolocator: ^10.0.1
  swipeable_button_view: ^0.0.2
  get_storage: ^2.1.1
  audioplayers: ^5.1.0
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true


  assets:
    - assets/

